"""fixed price column name and relationship names

Revision ID: 9a847782d832
Revises: c1246174de7e
Create Date: 2026-08-31 23:19:58.046871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a847782d832'
down_revision: Union[str, Sequence[str], None] = 'c1246174de7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_cents', sa.Integer(), nullable=False))
    op.drop_column('products', 'prince_cents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prince_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'price_cents')
    # ### end Alembic commands ###
